In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
df=pd.read_csv("uci_malware_detection1.csv")

In [3]:
df.head()

,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,F_10,...,F_523,F_524,F_525,F_526,F_527,F_528,F_529,F_530,F_531,target
0,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
x=df.drop(columns=['target'])
y=df['target']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

clf=RandomForestClassifier(n_estimators=100)
clf=clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
print("Dogruluk skoru : ",accuracy_score(y_test, y_pred))

Dogruluk skoru :  0.9821428571428571